In [2]:
import torch

In [6]:
# Imagine a simple neuron
input_features=3
output_features=1

In [14]:
# lEARNABLE PARAMETERS
W=torch.randn(input_features, output_features, requires_grad=True)
b=torch.zeros(output_features, requires_grad=True)
print(b)
print(W)
W+b



tensor([0.], requires_grad=True)
tensor([[ 2.4866],
        [-0.8765],
        [-0.9954]], requires_grad=True)


tensor([[ 2.4866],
        [-0.8765],
        [-0.9954]], grad_fn=<AddBackward0>)

In [16]:
# One sample

x=torch.tensor([[1.0, 2.5, -1.0]])
x

tensor([[ 1.0000,  2.5000, -1.0000]])

In [21]:
# Forward pass
z=x@W +b
y=torch.sigmoid(z)   # Activation
y

tensor([[0.7843]], grad_fn=<SigmoidBackward0>)

In [23]:
# Backpropagation
loss=(y-0.8)**2
loss

tensor([[0.0002]], grad_fn=<PowBackward0>)

In [24]:
# loss - backpropagation
loss.backward()

print("Gradient of W: ", W.grad) 
print("Gradient of b:", b.grad)

Gradient of W:  tensor([[-0.0053],
        [-0.0133],
        [ 0.0053]])
Gradient of b: tensor([-0.0053])


# 2. ANN — Artificial Neural Networks