## 7.3 Linear Algebra Operations

In [5]:
import torch
import time

start=time.time();
A=torch.randn(4, 4)
print(A)
print(f"Time it rand was : {time.time() - start:.4f}s")

tensor([[ 1.3522,  0.6748, -0.1317,  1.0306],
        [ 1.5040, -0.7274,  0.6001,  0.6641],
        [ 0.4045,  0.1917,  1.4517,  0.2310],
        [ 0.2179, -0.9863, -0.0989,  2.4155]])
Time it rand was : 0.0020s


In [8]:
# Determinant
det=torch.linalg.det(A);
# inverse
A_inv=torch.linalg.inv(A)
print(f"The determinant of A is: {det}");
print(f"The inverse of A is: {A_inv}")

The determinant of A is: -7.648015022277832
The inverse of A is: tensor([[ 0.2672,  0.5137, -0.2041, -0.2357],
        [ 0.5904, -0.5920,  0.2903, -0.1169],
        [-0.1858, -0.0190,  0.6811,  0.0193],
        [ 0.2094, -0.2888,  0.1648,  0.3883]])


In [11]:
eigenvalues, eigenvectors=torch.linalg.eig(A)
print(f"The value of eigen vector is: {eigenvalues}")

The value of eigen vector is: tensor([-1.1467+0.0000j,  1.2875+0.0000j,  2.1756+0.6682j,  2.1756-0.6682j])


In [13]:
# Singular Value Decomposition (SVD)
# Used in attention mechanisms, dimensionality reduction
U, S, Vh = torch.linalg.svd(A)
U

tensor([[-0.4240, -0.3233,  0.7776, -0.3333],
        [-0.4913, -0.4374, -0.1319,  0.7415],
        [-0.1695, -0.5794, -0.5715, -0.5558],
        [-0.7417,  0.6070, -0.2265, -0.1737]])

In [18]:
torch.linalg.norm(A) # Frobenius norm of matrix

tensor(4.0226)

In [19]:
torch.linalg.norm(A, dim=1)  # l2 norm of each row

tensor([1.8339, 1.8953, 1.5367, 2.6201])

In [22]:
# solve linear system : Ax=b
b=torch.randn(4)
x=torch.linalg.solve(A, b)
x

tensor([-0.1979,  0.3047, -0.6406,  0.3949])