# Basics of OOP

In [7]:
# A class is a blueprint for crewating objects
class Animal:
    # init is going to run when we create an instance
    def __init__(self, name, sound):
        self.name=name
        self.sound=sound
        # instance attribute as seen above

        # instance method
    def speak(self):
        return f"{self.name} says {self.sound}";
    def __repr__(self):
        return f"Animal(name={self.name})"



In [9]:
# Create instances
dog=Animal("Dog", "Woof")
cat=Animal("Cat", "Meow")
print(cat.speak())   # "Dog says woof"

Cat says Meow


In [12]:
class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(name, "woof") # Call parent'8.2 The nn.Module Pattern — The Core of PyTorch
 __init__
        self.breed=breed
    def fetch(self):
        return f"{self.name} fetches the ball!"
    # overrides the parent method
    def speak(self):
        return f"{self.name} barks loudly: WOOF WOOF!"
rex=Dog("Rex", "German shepherd")
print(rex.speak())
print(rex.fetch())

Rex barks loudly: WOOF WOOF!
Rex fetches the ball!


## 8.2 The nn.Module Pattern — The Core of PyTorch
Every neural network in PyTorch inherits from torch.nn.Module . This is the most important class in PyTorch.
When you inherit from nn.Module , your class gets superpowers:
Automatically tracks all nn.Parameter and sub-modules

In [20]:
import torch
import torch.nn as nn

class SimpleLinearModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        # Always call super.__init__() first - this initializes nn.Module
        super().__init__()
        # Define layers as attributes
        # nn.Module automatically register these as sub modules
        self.layer1=nn.Linear(input_size, hidden_size)
        self.activation=nn.ReLU()
        self.layer2=nn.Linear(hidden_size, output_size)
    def forward(self, x):
        # Define how data flows through the network
        # This is called when you do Model(x)
        x=self.layer1(x)  # Linear Transformatiom
        x=self.activation(x) #  Non-linearity
        x=self.layer2(x)   # Output Layer
        return x

# Create a model instance
model=SimpleLinearModel(input_size=10, hidden_size=64, output_size=3)

# Explore the model
print(model)
print(model.layer1)
        
# Count Parameters
total_params=sum(p.numel() for p in model.parameters());
trainable=sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of parameters are: {total_params}")
print(f"Total number opf trainable parameters are: {trainable}")



# DIFEREMTIATE BETWEEN TRAINABLE PARAMS AND PARAMS
        

SimpleLinearModel(
  (layer1): Linear(in_features=10, out_features=64, bias=True)
  (activation): ReLU()
  (layer2): Linear(in_features=64, out_features=3, bias=True)
)
Linear(in_features=10, out_features=64, bias=True)
Total number of parameters are: 899
Total number opf trainable parameters are: 899


# training a simpel neural network

using the iris dataset on iris flowers, neural nets to classify iris flowers

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [63]:
# Create a Model calss that inherits nn.Module
class Model(nn.Module):
    # input layer (4 features of the flower)--> Hidden layer1 (number of neurons)
    # -->H2(some number of neurons)
    # -->output (tell us one of our three  classes of iris flowers)
    def __init__(self, in_features=4,h1=8, h2=9, out_features=3):
        super().__init__()  #instantiate our nn.module
        # setup our layers
        # fc=fully connected
        self.fci=nn.Linear(in_features, h1)
        self.fc2=nn.Linear(h1, h2)
        self.out=nn.Linear(h2, out_features)

        # Create a function that moves everything forward:
    def forward(self, x):
        x=F.relu(self.fc1(x))
        x=F.relu(self.fc2(x))
        x=self.out(x)

        return x
    

In [64]:
# Create a random seed to reproduce random values
torch.manual_seed(42)
# create an instance of our model
model=Model()
model

Model(
  (fci): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)

In [62]:
model.parameters()

<generator object Module.parameters at 0x0000027687E6C7B0>

# Loading Real data

In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df=pd.read_csv("iris.csv")
df.head(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [17]:
# df['column_name'].unique() to get an array of all unique category names.

In [19]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [21]:
# changing our species colums to numbers
df["Species"]=df["Species"].replace("Iris-setosa", 0.0)
df["Species"]=df["Species"].replace("Iris-versicolor", 1.0)
df["Species"]=df["Species"].replace("Iris-virginica", 2.0)


# ___________________________or____________________________________________


# Create a mapping dictionary
# species_mapping = {
#     "Iris-setosa": 0.0, 
#     "Iris-versicolor": 1.0, 
#     "Iris-virginica": 2.0
# }

# # Apply the mapping
# df["Species"] = df["Species"].map(species_mapping

C:\Users\THE EYE INFORMATIQUE\AppData\Local\Temp\ipykernel_25780\2411632222.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"]=df["Species"].replace("Iris-virginica", 2.0)


In [29]:
df.tail(100)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,1.0
51,52,6.4,3.2,4.5,1.5,1.0
52,53,6.9,3.1,4.9,1.5,1.0
53,54,5.5,2.3,4.0,1.3,1.0
54,55,6.5,2.8,4.6,1.5,1.0
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,2.0
146,147,6.3,2.5,5.0,1.9,2.0
147,148,6.5,3.0,5.2,2.0,2.0
148,149,6.2,3.4,5.4,2.3,2.0


In [38]:
# Start train. Test and Split things
X=df.drop("Species", axis=1)
y=df["Species"]
x

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
0,1,5.1,3.5,1.4,0.2
1,2,4.9,3.0,1.4,0.2
2,3,4.7,3.2,1.3,0.2
3,4,4.6,3.1,1.5,0.2
4,5,5.0,3.6,1.4,0.2
...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3
146,147,6.3,2.5,5.0,1.9
147,148,6.5,3.0,5.2,2.0
148,149,6.2,3.4,5.4,2.3


In [39]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: Species, Length: 150, dtype: float64

In [40]:
X.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
dtype: object

In [45]:
# Convert data to numpy array
X=X.values
y=y.values


AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [46]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2,random_state=42)
X_train

array([[2.30e+01, 4.60e+00, 3.60e+00, 1.00e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [6.60e+01, 6.70e+00, 3.10e+00, 4.40e+00, 1.40e+00],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [4.30e+01, 4.40e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [1.47e+02, 6.30e+00, 2.50e+00, 5.00e+00, 1.90e+00],
       [5.20e+01, 6.40e+00, 3.20e+00, 4.50e+00, 1.50e+00],
       [2.80e+01, 5.20e+00, 3.50e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [3.30e+01, 5.20e+00, 4.10e+00, 1.50e+00, 1.00e-01],
       [1.43e+02, 5.80e+00, 2.70e+00, 5.10e+00, 1.90e+00],
       [8.60e+01, 6.00e+00, 3.40e+00, 4.50e+00, 1.60e+00],
       [8.70e+01, 6.70e+00, 3.10e+00, 4.70e+00, 1.50e+00],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [8.20e+01, 5.50e+00, 2.40e+00, 3.70e+00, 1.00e+00],
       [1.34e+02, 6.30e+00, 2.80e+00, 5.10e+00, 1.50e+00

In [55]:
# Convert numpy arrays to tensors
X_train=torch.FloatTensor(X_train)
X_test=torch.FloatTensor(X_test)
y_train=torch.LongTensor(y_train)
y_test=torch.LongTensor(y_test)
# long tensors are 62 bits integers
y_test
# X_train

tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
        2, 2, 2, 2, 0, 0])

In [59]:
# sET THE CRITERION OF OUR MODEL TO MEASURE THE ERRRO
criterion=nn.CrossEntropyLoss()

# choose an optimizer (Adam optimizer) and and a learning  rate
optimizer=torch.optim.Adam(model.parameters(), lr=0.01)
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

In [67]:
model.parameters

<bound method Module.parameters of Model(
  (fci): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>

In [ ]:
# TrAIN OUR MODEL [how many epochs do we want ... one run through our neural network in a time]
epochs=100
losses=[]
for i in range(epochs):
    # go forward and get a prediction
    y_pred=model.forward(x_train)  #get predicted results
    # criteriom
    loss=criterion(y_pred, y_train) # predicted values vs the y_trai