**How Python lists store data in memory:**

```
Memory:
[ptr→1] [ptr→2] [ptr→3] [ptr→4] [ptr→5]
  ↓        ↓       ↓       ↓       ↓
 (int)   (int)  (int)   (int)  (int)
```

Each element is a **pointer to a Python object**. Python objects carry overhead (type info, reference count, etc.). A list of 1 million integers uses ~8 MB just for pointers, plus ~28 bytes per integer object = ~35 MB total.

**Limitations for deep learning:**

- Extremely slow for mathematical operations (loop overhead)
- Cannot run on GPU
- No vectorized math (must loop)
- High memory overhead

In [2]:
my_list=[1,2,3,4,5]
nested_list=[[1,2], [3,4]]  # 2d list

my_list
nested_list[0][1]

2

In [6]:
# operations
print(my_list[0]);
print(my_list + [6])
new_list=[x*2 for x in my_list if x%2==0]
new_list

1
[1, 2, 3, 4, 5, 6]


[4, 8]

### NumPy Arrays

NumPy is a library for **numerical computing in Python**. Its `ndarray` (N-dimensional array) stores data in a **contiguous block of memory** of a single type.

**How NumPy stores data:**

```
Memory (contiguous):
[1.0][2.0][3.0][4.0][5.0]
 f32  f32  f32  f32  f32
```

All elements are the same type, packed tightly. Operations can use SIMD (CPU vectorization) and are implemented in C — very fast.

**Limitations for deep learning:**

- Still CPU-only (no GPU support)
- No automatic gradient computation
- Not designed for deep learning workflows

In [15]:
import numpy as np
# Creating arrays
arr=np.array([1,2,3,4,5])
# matrix
matrix=np.array([[1,2], [3,4]])
# shape and dimensions
print(arr.shape)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

# vectorise operations
arr2=arr *2
arr3=np.sqrt(arr)
dot=matrix @ matrix
print(arr2)
print(dot)
print(arr3)

(5,)
(2, 2)
2
int64
[ 2  4  6  8 10]
[[ 7 10]
 [15 22]]
[1.         1.41421356 1.73205081 2.         2.23606798]


### PyTorch Tensors

A PyTorch tensor is like a NumPy array but with two superpowers:

1. **Can live on GPU** — operations run in parallel on thousands of GPU cores
2. **Tracks operations for automatic differentiation** (autograd)

In [22]:
import torch
# creating tensors
t1=torch.tensor([1,2,3,4,5], dtype=torch.float32)
t1

tensor([1., 2., 3., 4., 5.])