In [ ]:
# simple deeplearning implementation in numpy
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Setup data -> 3 inputs -> 2 outputs
N=100;
print(N)

100


In [5]:
X=np.random.randn(N, 3)
X

array([[-0.67106253, -2.40332198, -1.47690092],
       [-1.05316496,  0.18417059,  0.42454134],
       [-0.52539555, -1.84588864, -0.27320069],
       [-0.47132768,  0.66385908, -1.47051476],
       [ 0.53176708,  1.8690674 , -3.49435875],
       [-0.66628132, -0.52164833, -0.59216277],
       [-0.03641857, -0.47019225, -0.3025871 ],
       [-0.17860062, -0.48966693,  0.21757646],
       [ 0.21625317, -0.90931986,  1.05320102],
       [-2.24389228, -0.4618144 , -0.49240439],
       [-0.16578138, -1.4128465 ,  0.42424579],
       [-1.19583665,  0.82979695, -0.00476745],
       [ 0.77778226, -0.03056206, -0.31677725],
       [-0.64132943,  0.34949261, -0.17046211],
       [ 0.57604938,  0.30541808, -0.10894335],
       [ 1.02360629, -0.91260057, -1.60210433],
       [ 0.30630423,  0.39937993, -2.21015662],
       [-0.32282377, -0.40357926,  0.45898507],
       [ 0.06552382, -0.57404178,  0.58154907],
       [-0.70983207,  1.71320872, -0.96128222],
       [-0.08760845, -1.29385912,  1.739

In [8]:
# lets make it learn y1=x1+x2 and y2=x3*0.5
Y=np.zeros((N, 2))
Y

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [11]:
Y[:, 0]=X[:, 0] + X[:, 1]
Y[:, 1]=X[:, 2] * 0.5
print(Y)

[[-3.07438451e+00 -7.38450462e-01]
 [-8.68994365e-01  2.12270671e-01]
 [-2.37128419e+00 -1.36600343e-01]
 [ 1.92531399e-01 -7.35257382e-01]
 [ 2.40083447e+00 -1.74717937e+00]
 [-1.18792965e+00 -2.96081384e-01]
 [-5.06610827e-01 -1.51293551e-01]
 [-6.68267545e-01  1.08788231e-01]
 [-6.93066687e-01  5.26600512e-01]
 [-2.70570668e+00 -2.46202197e-01]
 [-1.57862789e+00  2.12122894e-01]
 [-3.66039699e-01 -2.38372573e-03]
 [ 7.47220201e-01 -1.58388625e-01]
 [-2.91836815e-01 -8.52310539e-02]
 [ 8.81467463e-01 -5.44716758e-02]
 [ 1.11005719e-01 -8.01052167e-01]
 [ 7.05684160e-01 -1.10507831e+00]
 [-7.26403021e-01  2.29492536e-01]
 [-5.08517959e-01  2.90774534e-01]
 [ 1.00337664e+00 -4.80641111e-01]
 [-1.38146756e+00  8.69883931e-01]
 [-6.68270798e-01 -4.22531962e-01]
 [-1.59880457e+00 -1.10305770e+00]
 [-1.76179961e+00 -1.27650741e+00]
 [-2.27942440e+00 -4.52905434e-01]
 [-1.30728997e+00  1.49285751e-01]
 [-1.00135385e+00  1.89115940e-01]
 [ 4.20693161e-01  6.26559026e-01]
 [ 2.80933488e+00 -5

In [17]:
# Imitilaize the weight
W1=np.random.randn(3,4) * 0.1
print(w1)

[[ 0.16916989 -0.04110168 -0.0410544  -0.03773001]
 [ 0.03939583  0.10780585  0.07322034 -0.09339732]
 [-0.0179015  -0.06819046 -0.01116978 -0.07459547]]


In [20]:
b1=np.zeros((1, 4))
W2 = np.random.randn(4, 4) * 0.1
b2 = np.zeros((1, 4))
W3 = np.random.randn(4, 2) * 0.1
b3 = np.zeros((1, 2))

In [23]:
print(W2)

[[ 0.05385523 -0.04641874  0.02684176 -0.21124297]
 [ 0.09682602 -0.1345223   0.13201475  0.04323992]
 [ 0.11160491 -0.07585221 -0.01852961 -0.13773947]
 [-0.00137352  0.04444965  0.04438244 -0.22133485]]


In [26]:
lr=0.01
history=[]
print(history)
print(lr)

[]
0.01


In [28]:
# 2 ttrainig the loop.

for i in range(1000):
    # forward pass
    x1=X@w1 + b1
    a1=np.maximum(0, z1) # Relu
    z2=ai@W2 + b2 
    az=np.maximum(0, z2) # Relu
    print("Hello, world")

    y_hat=a2@W3 + b3


NameError: name 'z1' is not defined