In [1]:
# simple deeplearning implementation in numpy
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Setup data -> 3 inputs -> 2 outputs
N=100;
print(N)

100


In [3]:
X=np.random.randn(N, 3)
X

array([[ 2.19228117, -0.9001145 ,  0.68033515],
       [ 1.07432559,  1.77687099, -1.39149783],
       [ 0.59527942,  0.47786855, -0.48071454],
       [ 0.27036949, -0.25362182,  1.37680893],
       [ 0.20126608,  1.39295946, -0.69249994],
       [-0.65660629,  1.5318135 , -0.62677113],
       [ 0.20395261, -2.14518115,  0.03498453],
       [ 1.54975762,  0.2212798 ,  0.09348187],
       [-0.35649591, -0.81443146, -0.08404447],
       [-0.60926485, -1.27486525,  0.39251404],
       [ 0.69901138, -0.55761006, -0.88955152],
       [ 0.18771737,  0.38381076, -0.3254094 ],
       [ 1.33046537,  0.60757212,  0.44539222],
       [ 0.34830652, -0.03491787, -0.59088836],
       [ 1.20813734,  0.77254143, -0.96266501],
       [ 0.03369855,  0.73959301,  0.19353339],
       [ 0.11068377,  0.23806511,  0.17046131],
       [-0.61756445, -0.19182314,  2.58165221],
       [-0.02711557, -1.06147335, -0.38145527],
       [ 0.62918368,  1.50073333,  1.57144415],
       [ 0.05682213,  0.80921736,  0.084

In [4]:
# lets make it learn y1=x1+x2 and y2=x3*0.5
Y=np.zeros((N, 2))
Y

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [5]:
Y[:, 0]=X[:, 0] + X[:, 1]
Y[:, 1]=X[:, 2] * 0.5
print(Y)

[[ 1.29216667  0.34016757]
 [ 2.85119658 -0.69574891]
 [ 1.07314797 -0.24035727]
 [ 0.01674767  0.68840446]
 [ 1.59422554 -0.34624997]
 [ 0.87520722 -0.31338557]
 [-1.94122853  0.01749226]
 [ 1.77103742  0.04674094]
 [-1.17092737 -0.04202224]
 [-1.88413011  0.19625702]
 [ 0.14140132 -0.44477576]
 [ 0.57152813 -0.1627047 ]
 [ 1.93803749  0.22269611]
 [ 0.31338865 -0.29544418]
 [ 1.98067876 -0.48133251]
 [ 0.77329156  0.09676669]
 [ 0.34874887  0.08523065]
 [-0.80938758  1.2908261 ]
 [-1.08858892 -0.19072763]
 [ 2.12991702  0.78572208]
 [ 0.86603949  0.04239922]
 [-0.72570208  0.13967206]
 [-0.17933155 -0.0240496 ]
 [ 1.83333788 -0.47846533]
 [-2.38432954  0.03661225]
 [-0.12584258  0.08853909]
 [ 0.12038298  0.05068625]
 [ 0.17060096 -0.5451088 ]
 [ 1.80183441 -0.1959336 ]
 [ 0.65521711  0.27548357]
 [-0.27457812 -0.22396248]
 [ 1.67315218  0.4352405 ]
 [ 1.11202193 -0.59080756]
 [-1.34358087  0.00866102]
 [ 1.64216496  0.51582285]
 [ 3.01554608  0.08368654]
 [ 0.95139785  1.10587537]
 

In [7]:
# Imitilaize the weight
W1=np.random.randn(3,4) * 0.1
print(W1)

[[-0.00144788 -0.09671622  0.10098572  0.04334907]
 [-0.02554901  0.03384711  0.10272709 -0.0232268 ]
 [-0.02456764 -0.11671912  0.21751566  0.00877635]]


In [8]:
b1=np.zeros((1, 4))
W2 = np.random.randn(4, 4) * 0.1
b2 = np.zeros((1, 4))
W3 = np.random.randn(4, 2) * 0.1
b3 = np.zeros((1, 2))

In [9]:
print(W2)

[[-0.02428675  0.05192324 -0.00069168 -0.0702869 ]
 [ 0.12846408 -0.02602899 -0.19907245 -0.11069813]
 [ 0.09769262  0.19765587  0.0404877  -0.07020527]
 [ 0.23684464 -0.01876458  0.27534854  0.01607577]]


In [10]:
lr=0.01
history=[]
print(history)
print(lr)

[]
0.01


In [14]:
# 2 ttrainig the loop.

for i in range(1000):
    # forward pass
    x1=X@W1 + b1
    a1=np.maximum(0, x1) # Relu
    z2=a1@W2 + b2 
    a2=np.maximum(0, z2) # Relu
    print("Hello, world")

    y_hat=a2@W3 + b3

    # Loss (mse)
    loss=np.mean((y_hat - Y)**2)
    history.append(loss)
    # __Backward pass__
    # layer 3
    dy_hat=2.0*(y_hat-Y)/N
    dW3=a2.T @ dy_hat
    db3=np.sum(dy_hat, axis=0, keepdims=True)
    da2=dy_hat @ W3.T
      # Layer 2
    dz2 = da2.copy()
    dz2[z2 <= 0] = 0 # ReLU backward
    dW2 = a1.T @ dz2
    db2 = np.sum(dz2, axis=0, keepdims=True)
    da1 = dz2 @ W2.T
    
    # Layer 1
    dz1 = da1.copy()
    dz1[z1 <= 0] = 0 # ReLU backward
    dW1 = X.T @ dz1
    db1 = np.sum(dz1, axis=0, keepdims=True)
    # --- UPDATE ---
    W3 -= lr * dW3
    b3 -= lr * db3
    W2 -= lr * dW2
    b2 -= lr * db2
    W1 -= lr * dW1
    b1 -= lr * db1

    # 4. VISUALIZATION
    plt.figure(figsize=(10, 4))
    plt.plot(history)
    plt.yscale('log')
    plt.title("Loss Training Curve (3-4-4-2 Network)")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()
    
    


Hello, world


NameError: name 'z1' is not defined