In [1]:
# Pytorch Maths

## 7.1 Element-wise Operations


In [8]:
import torch

a=torch.tensor([1.0,4.0, 9.0, 16.0])
b=torch.tensor([2.0,2.0, 3.0, 4.0])
print(a)
print(b)

tensor([ 1.,  4.,  9., 16.])
tensor([2., 2., 3., 4.])


In [14]:
# Arithmeic

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
# floor division
print(a//b)
# mudolo
print(a%b)

tensor([ 3.,  6., 12., 20.])
tensor([-1.,  2.,  6., 12.])
tensor([ 2.,  8., 27., 64.])
tensor([0.5000, 2.0000, 3.0000, 4.0000])
tensor([1.0000e+00, 1.6000e+01, 7.2900e+02, 6.5536e+04])
tensor([0., 2., 3., 4.])
tensor([1., 0., 0., 0.])


In [17]:
# Maths functions
print(torch.sqrt(a))
print(torch.exp(a))  # e^a element-wise
print(torch.log(a)) # natural log
print(torch.log2(a)) # log base 2
print(torch.abs(a))
print(torch.ceil(a)) #round up
print(torch.floor(a)) #round down
print(torch.clip(a, 2, 8)) # clip a between [2, 8]

tensor([1., 2., 3., 4.])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03, 8.8861e+06])
tensor([0.0000, 1.3863, 2.1972, 2.7726])
tensor([0.0000, 2.0000, 3.1699, 4.0000])
tensor([ 1.,  4.,  9., 16.])
tensor([ 1.,  4.,  9., 16.])
tensor([ 1.,  4.,  9., 16.])
tensor([2., 4., 8., 8.])


## 7.2 Broadcasting

Broadcasting is how PyTorch (and NumPy) handle math between tensors of different shapes. It's essential for
understanding how batches and bias terms work.


In [25]:
# Rule: dimensions are aligned from RIGHT, and dimensions of size 1 stretch

a=torch.ones(3,4)
b=torch.ones(4)
print(a)
print(b)
print(a+b) # [3,4] + [4] -> b broadcast to [3, 4]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [26]:
# Concrete example: adding bias to a batch

batch=torch.randn(32, 10); # 32 samples, 10 features
bias=torch.randn(10)  # One bias per feature
result=batch  + bias;
print(f"Result is: {result}")
print(batch)


Result is: tensor([[-1.6633e+00, -4.8659e-01,  9.5530e-01, -5.6683e-01, -3.8767e-02,
          9.3825e-01,  5.8510e-01,  1.3585e+00, -1.0914e+00,  1.0575e+00],
        [ 8.7950e-03, -2.2504e+00, -9.3081e-02,  3.9301e-01,  2.2722e+00,
         -6.1730e-01,  1.9005e+00,  1.7616e+00,  5.1320e-01, -5.5977e-01],
        [-2.3203e+00, -2.2852e+00, -1.0991e+00, -2.5524e+00, -7.1983e-01,
          2.3203e-02,  1.8789e+00,  2.3440e+00,  9.7398e-01,  7.1777e-01],
        [ 2.8915e+00, -1.2915e-01,  1.3246e+00, -2.9746e+00,  8.9248e-01,
          9.8128e-01,  9.8226e-01,  1.5662e+00,  7.1441e-02,  2.2251e+00],
        [-6.6061e-01,  3.4828e-01, -7.7574e-01, -1.9699e+00,  1.7509e+00,
          1.2692e+00,  5.6271e-01,  1.5737e+00, -1.9237e+00, -1.6172e-01],
        [ 1.1038e+00, -1.6716e+00, -4.3534e-01, -1.4593e+00, -1.1180e+00,
          7.7475e-01,  1.0081e+00,  2.0713e+00,  4.4817e-01,  8.6049e-01],
        [ 2.7819e+00,  1.0042e+00, -3.9514e-01, -5.4318e-01,  1.3264e+00,
         -1.0091e-01,

In [30]:
# Another example: normalizing each sample
data=torch.randn(32, 100)     # [32, 100]
print(data)
# print(data.size())
means=data.mean(dim=1, keepdim=True) # [32, 1]  -> keepdim is crucial here
stds=data.std(dim=1, keepdim=True) # [32, 1]
normalized=(data-means)

tensor([[-0.9785,  0.0540,  1.3691,  ...,  0.3433,  1.3571,  1.0922],
        [ 2.4179,  0.7963,  1.1540,  ..., -0.0569,  1.5206, -0.1100],
        [-0.9152,  1.6883, -0.3310,  ...,  1.2046, -1.4196, -0.0030],
        ...,
        [-2.1600, -0.0287,  0.6414,  ..., -1.3054, -1.0450,  0.4084],
        [ 0.0582, -0.2817, -0.2606,  ...,  0.5586,  0.4447, -0.4992],
        [-0.9802,  1.5276, -0.5608,  ...,  0.2681, -0.4916,  1.7824]])
torch.Size([32, 100])
