In [3]:
import torch
import tensorflow as tf

print(tf.__version__)

2.21.0


In [5]:
print("hello")

hello


In [6]:
import sys
print(f"Python: {sys.version}")
print(f"TensorFlow: {tf.__version__}")
print(f"Keras: {tf.keras.__version__}")
# GPU details
gpus = tf.config.list_physical_devices('GPU')
print(f"\nGPUs found: {len(gpus)}")


Python: 3.10.20 | packaged by Anaconda, Inc. | (main, Mar 11 2026, 17:42:35) [MSC v.1942 64 bit (AMD64)]
TensorFlow: 2.21.0
Keras: 3.12.4

GPUs found: 0


In [8]:
a=tf.constant([1.0, 4.0, 9.0, 16.0])
b=tf.constant([2.0, 2.0, 3.0, 4.0])
a + b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  6., 12., 20.], dtype=float32)>

In [10]:
tf.sqrt(a)
tf.exp(a)
tf.math.log(a)
tf.math.log(a)/tf.math.log(2.0)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.      , 2.      , 3.169925, 4.      ], dtype=float32)>

In [12]:
tf.abs(a)
tf.sign(a)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

## 7.2 Broadcasting

Broadcasting rules are identical to NumPy and PyTorch. The implem

In [15]:
import tensorflow as tf
batch=tf.random.normal([32, 10])
batch

biase=tf.random.normal([10])
result=batch + biase

In [17]:
result

<tf.Tensor: shape=(32, 10), dtype=float32, numpy=
array([[ 0.24548852,  1.5421814 ,  0.665132  ,  1.5654645 ,  1.0564035 ,
        -0.85645616, -0.8866565 ,  0.47760135, -0.9797381 ,  0.7447321 ],
       [-0.40522313,  1.5845126 ,  0.8398863 ,  3.557783  , -1.2999165 ,
         0.34606874, -2.5474322 ,  1.7545973 ,  0.15653712, -1.9490228 ],
       [-0.3282253 , -0.22540122, -0.05463428,  0.24868906,  0.47347486,
         1.6243577 ,  0.809167  ,  1.8908606 , -1.57903   ,  0.03964019],
       [-1.122923  ,  0.4647856 , -0.4401737 ,  3.3558576 , -1.017631  ,
         2.0456305 , -1.6029252 ,  1.5984603 , -0.5103879 , -0.8086812 ],
       [-3.726615  ,  2.5318632 , -1.3478271 ,  2.5251222 , -0.31135267,
         1.4937277 ,  0.2337102 ,  0.8494443 , -1.5595925 ,  0.74349886],
       [-1.2300978 ,  0.6221321 , -0.744465  ,  3.8160565 ,  0.55440694,
         3.6484387 ,  0.72085714,  0.11478102, -1.9918953 ,  0.96826845],
       [-0.10921091, -0.3548553 ,  1.71098   ,  3.1831274 ,  1.86989

In [ ]:
# Normalize each sampple